FROM python:3.10
WORKDIR "/flats_project"

ENV PYTHONPATH "${PYTHONPATH}:/flats_project"

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

WORKDIR /flats_project/spider/crawler/spiders

CMD ["scrapy", "crawl", "flats"]