FROM python:3.10
WORKDIR "/flats_project"

ENV PYTHONPATH "${PYTHONPATH}:/flats_project"

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "flask_server.server:app"]
