CREATE TABLE IF NOT EXISTS flats (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS images (
    id SERIAL PRIMARY KEY,
    flat_id INTEGER NOT NULL,
    url VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY (flat_id) REFERENCES flats(id) ON DELETE CASCADE
);